/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomSelectRouteImport } from './routes/custom-select'
import { Route as MarqueeMotionRouteImport } from './routes/marquee-motion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomSelectRoute = CustomSelectRouteImport.update({
  id: '/custom-select',
  path: '/custom-select',
  getParentRoute: () => rootRouteImport,
} as any)
const MarqueeMotionRoute = MarqueeMotionRouteImport.update({
  id: '/marquee-motion',
  path: '/marquee-motion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom-select': typeof CustomSelectRoute
  '/marquee-motion': typeof MarqueeMotionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom-select': typeof CustomSelectRoute
  '/marquee-motion': typeof MarqueeMotionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom-select': typeof CustomSelectRoute
  '/marquee-motion': typeof MarqueeMotionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/custom-select' | '/marquee-motion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/custom-select' | '/marquee-motion'
  id: '__root__' | '/' | '/custom-select' | '/marquee-motion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomSelectRoute: typeof CustomSelectRoute
  MarqueeMotionRoute: typeof MarqueeMotionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-select': {
      id: '/custom-select'
      path: '/custom-select'
      fullPath: '/custom-select'
      preLoaderRoute: typeof CustomSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marquee-motion': {
      id: '/marquee-motion'
      path: '/marquee-motion'
      fullPath: '/marquee-motion'
      preLoaderRoute: typeof MarqueeMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomSelectRoute: CustomSelectRoute,
  MarqueeMotionRoute: MarqueeMotionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
